// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"adx-admin/api"
	"adx-admin/internal/domian/service"
	"adx-admin/internal/infrastructure/persistence"
	"adx-admin/pkg/configer"
	"adx-admin/pkg/core/app"
	"adx-admin/pkg/database/redshift"
	"adx-admin/pkg/microlog"
	"adx-admin/pkg/server"
)

// Injectors from wire.go:

func wireApp(config *configer.Config, logger microlog.Logger) (*app.App, func(), error) {
	redshiftRedshift := redshift.NewDatabase(config)
	healthApi := api.NewHealthApi()
	reportRepo := persistence.NewRShiftReportRepo(redshiftRedshift)
	reportService := service.NewReportService(reportRepo)
	reportApi := api.NewReportApi(logger, reportService)
	engine := server.NewEngine(healthApi, reportApi)
	serverServer := server.NewServer(config, engine, logger)
	appApp := app.NewApp(redshiftRedshift, serverServer, logger)
	return appApp, func() {
	}, nil
}
